### ISSUE TITLE
Plugin Should Not Force Globally-scoped Properties

### ISSUE THREAD

**Issue by EarthCitizen** [calgaryscientific/veracode-gradle-plugin#46]
VeracodeGetSandboxListTask constructor:
`app_id = project.findProperty('app_id')`

It is bad practice to force users of the plugin to use pre-defined globally-scoped properties. The defaults should only come from `veracodeSetup {}`, then it should be left up to the users how to get those values into their build.

The tasks should be getting their defaults from the `veracodeSetup` extension as well.

The plugin could get defaults from properties, but they should be scoped along the lines of:

`com.calgaryscientific.veracode.appId`
`com.calgaryscientific.veracode.buildId`
`com.calgaryscientific.veracode.username`

**Comment by DavidGamba** [comment]
I just released https://github.com/calgaryscientific/veracode-gradle-plugin/releases/tag/v0.6.0 

This addresses the use of global properties. 
Thanks for bringing it up!
